//! Secure Random Number Generation - Hardened Edition
//!
//! Provides cryptographically secure random number generation
//! with entropy mixing and fallback mechanisms.

use super::{CryptoError, CryptoResult};
use rand_core::{CryptoRng, RngCore, SeedableRng};
use rand::rngs::OsRng;
use zeroize::{Zeroize, ZeroizeOnDrop};

/// Minimum entropy threshold (in bits)
const MIN_ENTROPY_BITS: usize = 256;

/// Entropy pool size
const ENTROPY_POOL_SIZE: usize = 64;

/// Secure Random Number Generator
///
/// Uses OS-provided CSPRNG with additional entropy mixing.
/// Implements ZeroizeOnDrop for secure cleanup.
#[derive(Clone)]
pub struct SecureRandom {
    /// The underlying OS RNG
    rng: OsRng,
    /// Entropy pool for mixing
    entropy_pool: [u8; ENTROPY_POOL_SIZE],
    /// Number of bytes generated
    bytes_generated: u64,
    /// Maximum bytes before reseeding
    max_bytes_before_reseed: u64,
}

impl SecureRandom {
    /// Create a new secure random number generator
    ///
    /// # Errors
    /// Returns `CryptoError::RandomFailed` if the OS RNG fails
    pub fn new() -> CryptoResult<Self> {
        let mut rng = OsRng;
        
        // Initialize entropy pool
        let mut entropy_pool = [0u8; ENTROPY_POOL_SIZE];
        rng.fill_bytes(&mut entropy_pool);
        
        // Verify we got good entropy
        if entropy_pool.iter().all(|&b| b == 0) {
            return Err(CryptoError::RandomFailed);
        }
        
        Ok(Self {
            rng,
            entropy_pool,
            bytes_generated: 0,
            max_bytes_before_reseed: 1_000_000, // Reseed after 1MB
        })
    }

    /// Fill a buffer with random bytes
    ///
    /// # Arguments
    /// * `buf` - Buffer to fill with random bytes
    ///
    /// # Security
    /// - Uses OS CSPRNG
    /// - Mixes with entropy pool
    /// - Checks for reseeding needs
    pub fn fill_bytes(&mut self, buf: &mut [u8]) {
        // Check if we need to reseed
        if self.bytes_generated + buf.len() as u64 > self.max_bytes_before_reseed {
            self.reseed();
        }
        
        // Fill with OS random
        self.rng.fill_bytes(buf);
        
        // Mix with entropy pool (XOR)
        for (i, byte) in buf.iter_mut().enumerate() {
            *byte ^= self.entropy_pool[i % ENTROPY_POOL_SIZE];
        }
        
        // Update entropy pool
        self.update_entropy_pool(buf);
        
        // Track bytes generated
        self.bytes_generated += buf.len() as u64;
    }

    /// Generate a random u64
    pub fn next_u64(&mut self) -> u64 {
        let mut buf = [0u8; 8];
        self.fill_bytes(&mut buf);
        u64::from_le_bytes(buf)
    }

    /// Generate a random u32
    pub fn next_u32(&mut self) -> u32 {
        let mut buf = [0u8; 4];
        self.fill_bytes(&mut buf);
        u32::from_le_bytes(buf)
    }

    /// Generate a random boolean
    pub fn next_bool(&mut self) -> bool {
        self.next_u32() & 1 == 1
    }

    /// Generate a random value in range [0, max)
    ///
    /// # Security
    /// Uses rejection sampling to avoid bias
    pub fn gen_range(&mut self, max: u64) -> u64 {
        if max == 0 {
            return 0;
        }
        
        // Use rejection sampling for uniform distribution
        let mask = max.next_power_of_two() - 1;
        loop {
            let val = self.next_u64() & mask;
            if val < max {
                return val;
            }
        }
    }

    /// Generate a random value in range [min, max)
    pub fn gen_range_inclusive(&mut self, min: u64, max: u64) -> u64 {
        min + self.gen_range(max - min)
    }

    /// Generate random bytes into a new vector
    pub fn gen_bytes(&mut self, len: usize) -> Vec<u8> {
        let mut buf = vec![0u8; len];
        self.fill_bytes(&mut buf);
        buf
    }

    /// Reseed the RNG with fresh entropy
    fn reseed(&mut self) {
        // Get fresh entropy from OS
        self.rng.fill_bytes(&mut self.entropy_pool);
        self.bytes_generated = 0;
    }

    /// Update entropy pool with generated bytes
    fn update_entropy_pool(&mut self, generated: &[u8]) {
        // Simple entropy mixing using XOR and rotation
        for (i, &byte) in generated.iter().enumerate() {
            let idx = i % ENTROPY_POOL_SIZE;
            self.entropy_pool[idx] = self.entropy_pool[idx]
                .wrapping_add(byte)
                .rotate_left(3);
        }
    }

    /// Get bytes generated count
    pub fn bytes_generated(&self) -> u64 {
        self.bytes_generated
    }

    /// Check if reseeding is needed
    pub fn needs_reseed(&self) -> bool {
        self.bytes_generated >= self.max_bytes_before_reseed
    }
}

impl Default for SecureRandom {
    fn default() -> Self {
        Self::new().expect("Failed to initialize secure random")
    }
}

impl Zeroize for SecureRandom {
    fn zeroize(&mut self) {
        self.entropy_pool.zeroize();
        self.bytes_generated = 0;
    }
}

impl ZeroizeOnDrop for SecureRandom {}

impl RngCore for SecureRandom {
    fn next_u32(&mut self) -> u32 {
        self.next_u32()
    }

    fn next_u64(&mut self) -> u64 {
        self.next_u64()
    }

    fn fill_bytes(&mut self, dest: &mut [u8]) {
        self.fill_bytes(dest);
    }

    fn try_fill_bytes(&mut self, dest: &mut [u8]) -> Result<(), rand_core::Error> {
        self.fill_bytes(dest);
        Ok(())
    }
}

impl CryptoRng for SecureRandom {}

/// Thread-local secure random generator
thread_local! {
    static THREAD_RNG: std::cell::RefCell<SecureRandom> = 
        std::cell::RefCell::new(SecureRandom::new().expect("Failed to initialize thread RNG"));
}

/// Get thread-local secure random
pub fn thread_rng() -> impl FnMut() -> SecureRandom {
    || SecureRandom::new().expect("Failed to create RNG")
}

/// Generate random bytes using thread-local RNG
pub fn random_bytes(buf: &mut [u8]) {
    THREAD_RNG.with(|rng| {
        rng.borrow_mut().fill_bytes(buf);
    });
}

/// Generate a random u64 using thread-local RNG
pub fn random_u64() -> u64 {
    THREAD_RNG.with(|rng| {
        rng.borrow_mut().next_u64()
    })
}

/// Generate a random u32 using thread-local RNG
pub fn random_u32() -> u32 {
    THREAD_RNG.with(|rng| {
        rng.borrow_mut().next_u32()
    })
}

/// Generate random bytes into a new vector
pub fn random_vec(len: usize) -> Vec<u8> {
    let mut buf = vec![0u8; len];
    random_bytes(&mut buf);
    buf
}

/// Securely shuffle a slice (Fisher-Yates)
pub fn shuffle<T>(slice: &mut [T]) {
    let len = slice.len();
    if len <= 1 {
        return;
    }
    
    THREAD_RNG.with(|rng| {
        let mut rng = rng.borrow_mut();
        for i in (1..len).rev() {
            let j = rng.gen_range((i + 1) as u64) as usize;
            slice.swap(i, j);
        }
    });
}

/// Generate a random alphanumeric string
pub fn random_alphanumeric(len: usize) -> String {
    const CHARSET: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    
    THREAD_RNG.with(|rng| {
        let mut rng = rng.borrow_mut();
        (0..len)
            .map(|_| CHARSET[rng.gen_range(CHARSET.len() as u64) as usize] as char)
            .collect()
    })
}

/// Generate a random hex string
pub fn random_hex(len: usize) -> String {
    const HEX: &[u8] = b"0123456789abcdef";
    
    THREAD_RNG.with(|rng| {
        let mut rng = rng.borrow_mut();
        (0..len)
            .map(|_| HEX[rng.gen_range(16) as usize] as char)
            .collect()
    })
}

/// Check if system has sufficient entropy
pub fn check_entropy() -> CryptoResult<()> {
    // Try to generate some random bytes
    let mut buf = [0u8; 32];
    random_bytes(&mut buf);
    
    // Check if we got actual randomness
    if buf.iter().all(|&b| b == 0) {
        return Err(CryptoError::InsufficientEntropy);
    }
    
    // Check for patterns (simple check)
    let mut unique_bytes = std::collections::HashSet::new();
    for &b in &buf {
        unique_bytes.insert(b);
    }
    
    // Should have reasonable entropy
    if unique_bytes.len() < 8 {
        return Err(CryptoError::InsufficientEntropy);
    }
    
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_secure_random_creation() {
        let rng = SecureRandom::new();
        assert!(rng.is_ok());
    }

    #[test]
    fn test_fill_bytes() {
        let mut rng = SecureRandom::new().unwrap();
        let mut buf = [0u8; 32];
        rng.fill_bytes(&mut buf);
        
        // Should not be all zeros
        assert!(!buf.iter().all(|&b| b == 0));
    }

    #[test]
    fn test_random_uniqueness() {
        let mut rng = SecureRandom::new().unwrap();
        
        let mut buf1 = [0u8; 32];
        let mut buf2 = [0u8; 32];
        
        rng.fill_bytes(&mut buf1);
        rng.fill_bytes(&mut buf2);
        
        // Should be different (with extremely high probability)
        assert_ne!(buf1, buf2);
    }

    #[test]
    fn test_gen_range() {
        let mut rng = SecureRandom::new().unwrap();
        
        for _ in 0..100 {
            let val = rng.gen_range(100);
            assert!(val < 100);
        }
    }

    #[test]
    fn test_shuffle() {
        let mut arr: Vec<u8> = (0..100).collect();
        let original = arr.clone();
        
        shuffle(&mut arr);
        
        // Should have same elements
        arr.sort();
        assert_eq!(arr, original);
    }

    #[test]
    fn test_random_alphanumeric() {
        let s = random_alphanumeric(32);
        assert_eq!(s.len(), 32);
        assert!(s.chars().all(|c| c.is_ascii_alphanumeric()));
    }

    #[test]
    fn test_random_hex() {
        let s = random_hex(32);
        assert_eq!(s.len(), 32);
        assert!(s.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn test_check_entropy() {
        assert!(check_entropy().is_ok());
    }

    #[test]
    fn test_thread_rng() {
        let mut buf1 = [0u8; 32];
        let mut buf2 = [0u8; 32];
        
        random_bytes(&mut buf1);
        random_bytes(&mut buf2);
        
        assert_ne!(buf1, buf2);
    }

    #[test]
    fn test_random_vec() {
        let vec = random_vec(64);
        assert_eq!(vec.len(), 64);
    }

    #[test]
    fn test_reseed() {
        let mut rng = SecureRandom::new().unwrap();
        
        // Generate some bytes
        let mut buf = [0u8; 100];
        rng.fill_bytes(&mut buf);
        
        // Reseed
        rng.reseed();
        
        // Should still work
        rng.fill_bytes(&mut buf);
        assert!(!buf.iter().all(|&b| b == 0));
    }
}
